[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1"
console = "0.15"
unicode-width = "0.1"
indicatif = "0.17"
dialoguer = "0.11"
serde_json = "1.0"

config = { path = "../config" }
i18n = { path = "../i18n" }
